name: snapgallery
description: "An Flutter project using unsplash api."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_zoom_drawer: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  easy_refresh: ^3.4.0
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  injectable: ^2.4.2
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  share_plus: ^9.0.0
  flutter_cache_manager: ^3.3.2
  image_gallery_saver: ^2.0.3
  extended_image: ^8.2.1
  go_router: ^14.2.0
  flutter_dotenv: ^5.1.0
  flutter_webview_plugin: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  palette_generator: ^0.3.3+3
  pretty_dio_logger: ^1.3.1
  extended_nested_scroll_view: ^6.2.1





dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.1.4
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - .env
    - mock_data/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
