name: app
description: "An Flutter project using unsplash api."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_zoom_drawer: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  easy_refresh: ^3.4.0
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  injectable: ^2.4.2
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  share_plus: ^9.0.0
  flutter_cache_manager: ^3.3.2
  image_gallery_saver: ^2.0.3
  extended_image: ^8.2.1
  go_router: ^14.2.0
  flutter_webview_plugin: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  palette_generator: ^0.3.3+3
  extended_nested_scroll_view: ^6.2.1
  flutter_dotenv: ^5.1.0
  domain:
    path: ../packages/domain
  data:
    path: ../packages/data
  network: 
    path: ../packages/network
  common:
    path: ../packages/common
  initializer:    
    path: ../packages/initializer

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.1.4
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
