name: initializer
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  network:  
    path: ../network
  common: 
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
