name: domain
description: "domain module."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  injectable: ^2.4.2
  get_it: ^7.7.0
  common: 
    path: ../common

dev_dependencies:
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  